name: Publish to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # The github token is not set in the secrets for now. This is just to show the work flow
          publish_dir: ./statics_content